// Code generated by 'yaegi extract runtime/coverage'. DO NOT EDIT.

//go:build go1.25
// +build go1.25

package stdlib

import (
	"reflect"
	"runtime/coverage"
)

func init() {
	Symbols["runtime/coverage/coverage"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"ClearCounters":    reflect.ValueOf(coverage.ClearCounters),
		"WriteCounters":    reflect.ValueOf(coverage.WriteCounters),
		"WriteCountersDir": reflect.ValueOf(coverage.WriteCountersDir),
		"WriteMeta":        reflect.ValueOf(coverage.WriteMeta),
		"WriteMetaDir":     reflect.ValueOf(coverage.WriteMetaDir),
	}
}
