// Code generated by 'yaegi extract structs'. DO NOT EDIT.

//go:build go1.25
// +build go1.25

package stdlib

import (
	"reflect"
	"structs"
)

func init() {
	Symbols["structs/structs"] = map[string]reflect.Value{
		// type definitions
		"HostLayout": reflect.ValueOf((*structs.HostLayout)(nil)),
	}
}
