// Code generated by 'yaegi extract crypto/fips140'. DO NOT EDIT.

//go:build go1.25
// +build go1.25

package stdlib

import (
	"crypto/fips140"
	"reflect"
)

func init() {
	Symbols["crypto/fips140/fips140"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Enabled": reflect.ValueOf(fips140.Enabled),
	}
}
