// Code generated by 'yaegi extract crypto/pbkdf2'. DO NOT EDIT.

//go:build go1.25
// +build go1.25

package stdlib

import (
	"reflect"
)

func init() {
	Symbols["crypto/pbkdf2/pbkdf2"] = map[string]reflect.Value{}
}
