// Code generated by 'yaegi extract runtime/trace'. DO NOT EDIT.

//go:build go1.25
// +build go1.25

package stdlib

import (
	"reflect"
	"runtime/trace"
)

func init() {
	Symbols["runtime/trace/trace"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"IsEnabled":         reflect.ValueOf(trace.IsEnabled),
		"Log":               reflect.ValueOf(trace.Log),
		"Logf":              reflect.ValueOf(trace.Logf),
		"NewFlightRecorder": reflect.ValueOf(trace.NewFlightRecorder),
		"NewTask":           reflect.ValueOf(trace.NewTask),
		"Start":             reflect.ValueOf(trace.Start),
		"StartRegion":       reflect.ValueOf(trace.StartRegion),
		"Stop":              reflect.ValueOf(trace.Stop),
		"WithRegion":        reflect.ValueOf(trace.WithRegion),

		// type definitions
		"FlightRecorder":       reflect.ValueOf((*trace.FlightRecorder)(nil)),
		"FlightRecorderConfig": reflect.ValueOf((*trace.FlightRecorderConfig)(nil)),
		"Region":               reflect.ValueOf((*trace.Region)(nil)),
		"Task":                 reflect.ValueOf((*trace.Task)(nil)),
	}
}
