// Code generated by 'yaegi extract runtime/race'. DO NOT EDIT.

//go:build go1.25
// +build go1.25

package stdlib

import (
	"reflect"
)

func init() {
	Symbols["runtime/race/race"] = map[string]reflect.Value{}
}
