// Code generated by 'yaegi extract unique'. DO NOT EDIT.

//go:build go1.25
// +build go1.25

package stdlib

import (
	"reflect"
)

func init() {
	Symbols["unique/unique"] = map[string]reflect.Value{}
}
