// Code generated by 'yaegi extract log/syslog'. DO NOT EDIT.

//go:build go1.23 && !windows && !nacl && !plan9
// +build go1.23,!windows,!nacl,!plan9

package stdlib

import (
	"reflect"
)

func init() {
	Symbols["log/syslog/syslog"] = map[string]reflect.Value{}
}
