// Code generated by 'yaegi extract crypto/hkdf'. DO NOT EDIT.

//go:build go1.25
// +build go1.25

package stdlib

import (
	"reflect"
)

func init() {
	Symbols["crypto/hkdf/hkdf"] = map[string]reflect.Value{}
}
