// Code generated by 'yaegi extract testing/synctest'. DO NOT EDIT.

//go:build go1.25
// +build go1.25

package stdlib

import (
	"reflect"
	"testing/synctest"
)

func init() {
	Symbols["testing/synctest/synctest"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Test": reflect.ValueOf(synctest.Test),
		"Wait": reflect.ValueOf(synctest.Wait),
	}
}
