// Code generated by 'yaegi extract time/tzdata'. DO NOT EDIT.

//go:build go1.25
// +build go1.25

package stdlib

import (
	"reflect"
)

func init() {
	Symbols["time/tzdata/tzdata"] = map[string]reflect.Value{}
}
