// Code generated by 'yaegi extract crypto/mlkem'. DO NOT EDIT.

//go:build go1.25
// +build go1.25

package stdlib

import (
	"crypto/mlkem"
	"go/constant"
	"go/token"
	"reflect"
)

func init() {
	Symbols["crypto/mlkem/mlkem"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"CiphertextSize1024":       reflect.ValueOf(constant.MakeFromLiteral("1568", token.INT, 0)),
		"CiphertextSize768":        reflect.ValueOf(constant.MakeFromLiteral("1088", token.INT, 0)),
		"EncapsulationKeySize1024": reflect.ValueOf(constant.MakeFromLiteral("1568", token.INT, 0)),
		"EncapsulationKeySize768":  reflect.ValueOf(constant.MakeFromLiteral("1184", token.INT, 0)),
		"GenerateKey1024":          reflect.ValueOf(mlkem.GenerateKey1024),
		"GenerateKey768":           reflect.ValueOf(mlkem.GenerateKey768),
		"NewDecapsulationKey1024":  reflect.ValueOf(mlkem.NewDecapsulationKey1024),
		"NewDecapsulationKey768":   reflect.ValueOf(mlkem.NewDecapsulationKey768),
		"NewEncapsulationKey1024":  reflect.ValueOf(mlkem.NewEncapsulationKey1024),
		"NewEncapsulationKey768":   reflect.ValueOf(mlkem.NewEncapsulationKey768),
		"SeedSize":                 reflect.ValueOf(constant.MakeFromLiteral("64", token.INT, 0)),
		"SharedKeySize":            reflect.ValueOf(constant.MakeFromLiteral("32", token.INT, 0)),

		// type definitions
		"DecapsulationKey1024": reflect.ValueOf((*mlkem.DecapsulationKey1024)(nil)),
		"DecapsulationKey768":  reflect.ValueOf((*mlkem.DecapsulationKey768)(nil)),
		"EncapsulationKey1024": reflect.ValueOf((*mlkem.EncapsulationKey1024)(nil)),
		"EncapsulationKey768":  reflect.ValueOf((*mlkem.EncapsulationKey768)(nil)),
	}
}
